CDRIVER-3178 create Debian and RPM packages

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -47,6 +47,66 @@ functions:
           ${compile_env|} ./libmongocrypt/.evergreen/compile.sh
           ${test_env|} ./libmongocrypt/.evergreen/test.sh
 
+  "create packages and repos":
+    - command: expansions.update
+      params:
+        updates:
+        - key: version
+          value: $(sed -nE 's/^#define MONGOCRYPT_VERSION "([^"]+)".*/\1/p' libmongocrypt/src/mongocrypt.h)
+    - command: "shell.exec"
+      params:
+        script: |-
+          set -o xtrace
+          set -o errexit
+
+          if [ "${has_packages|}" != "true" ] ; then
+            echo "'has_packages' is not 'true', skipping package build"
+            exit 0
+          fi
+
+          # check if virtualenv is set up
+          if [ -d "${workdir}/venv" ]; then
+            if [ "Windows_NT" = "$OS" ]; then
+              # Need to quote the path on Windows to preserve the separator.
+              . "${workdir}/venv/Scripts/activate" 2> /tmp/activate_error.log
+            else
+              . ${workdir}/venv/bin/activate 2> /tmp/activate_error.log
+            fi
+            if [ $? -ne 0 ]; then
+              echo "Failed to activate virtualenv: $(cat /tmp/activate_error.log)"
+            fi
+            python=python
+          else
+            python=${python|/opt/mongodbtoolchain/v3/bin/python3}
+          fi
+
+          if [ "Windows_NT" = "$OS" ]; then
+            export PYTHONPATH="$PYTHONPATH;$(cygpath -w ${workdir}/src)"
+          else
+            export PYTHONPATH="$PYTHONPATH:${workdir}/src"
+          fi
+
+          pkg_version=${version}
+          tar -zcv -C install --transform="s+^libmongocrypt/+libmongocrypt-$pkg_version/+" --exclude=nocrypto -f libmongocrypt-$pkg_version.tar.gz libmongocrypt
+          cd libmongocrypt/etc/
+          $python ./packager.py --prefix `pwd`/.. --distros ${packager_distro} --tarball `pwd`/../../libmongocrypt-$pkg_version.tar.gz --library-version $pkg_version --metadata-gitspec HEAD --arches ${packager_arch}
+          cd ../..
+    - command: archive.targz_pack
+      params:
+        target: libmongocrypt-distro-packages.tar.gz
+        source_dir: libmongocrypt/repo
+        include: [./**]
+    - command: s3.put
+      params:
+        aws_key: '${aws_key}'
+        aws_secret: '${aws_secret}'
+        remote_file: '${project}/${build_variant}/${branch_name}/${libmongocrypt_s3_suffix}/libmongocrypt-distro-packages.tar.gz'
+        bucket: mciuploads
+        permissions: public-read
+        local_file: 'libmongocrypt-distro-packages.tar.gz'
+        content_type: '${content_type|application/x-gzip}'
+        optional: true
+
   "run clang-tidy":
     - command: "shell.exec"
       params:
@@ -104,6 +164,7 @@ tasks:
   - func: "fetch source"
   - func: "build and test"
   - func: "tar and upload libmongocrypt libraries"
+  - func: "create packages and repos"
 
 - name: clang-tidy
   commands:
@@ -197,8 +258,6 @@ tasks:
   depends_on:
     - variant: ubuntu1604
       name: build-and-test-and-upload
-    - variant: rhel76
-      name: build-and-test-and-upload
     - variant: macos
       name: build-and-test-and-upload
     - variant: rhel72-zseries-test
@@ -243,8 +302,6 @@ tasks:
         script: mkdir all
     - func: "download tarball"
       vars: { variant_name: ubuntu1604 }
-    - func: "download tarball"
-      vars: { variant_name: rhel76 }
     - func: "download tarball"
       vars: { variant_name: "macos" }
     - func: "download tarball"
@@ -347,6 +404,10 @@ buildvariants:
 - name: ubuntu1604
   display_name: "Ubuntu 16.04 64-bit"
   run_on: ubuntu1604-test
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1604
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -354,16 +415,6 @@ buildvariants:
   - build-and-test-asan
   - build-and-test-valgrind
   - build-and-test-java
-  - build-and-test-node
-- name: rhel76
-  display_name: "RHEL 7.6"
-  run_on: rhel76-test
-  tasks:
-  - clang-tidy
-  - build-and-test-and-upload
-  - build-and-test-shared-bson
-  - build-and-test-java
-  - build-csharp-and-test
   - build-and-test-node
 - name: macos
   display_name: "macOS 10.14"
@@ -378,6 +429,10 @@ buildvariants:
 - name: rhel72-zseries-test
   display_name: "RHEL 7.2 on zSeries"
   run_on: rhel72-zseries-test
+  expansions:
+    has_packages: true
+    packager_distro: rhel72
+    packager_arch: s390x
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -394,6 +449,10 @@ buildvariants:
 - name: linux-64-amazon-ami
   display_name: "Amazon Linux"
   run_on: amazon1-2018-test
+  expansions:
+    has_packages: true
+    packager_distro: amazon
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -403,6 +462,10 @@ buildvariants:
 - name: amazon2
   display_name: "Amazon Linux 2"
   run_on: amazon2-test
+  expansions:
+    has_packages: true
+    packager_distro: amazon2
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -413,6 +476,10 @@ buildvariants:
 - name: debian92
   display_name: "Debian 9.2"
   run_on: debian92-test
+  expansions:
+    has_packages: true
+    packager_distro: debian92
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -423,6 +490,10 @@ buildvariants:
 - name: rhel-62-64-bit
   display_name: "RHEL 6.2 64-bit"
   run_on: rhel62-small
+  expansions:
+    has_packages: true
+    packager_distro: rhel62
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -433,12 +504,20 @@ buildvariants:
 - name: rhel-67-s390x
   display_name: "RHEL 6.7 s390x"
   run_on: rhel67-zseries-test
+  expansions:
+    has_packages: true
+    packager_distro: rhel67
+    packager_arch: s390x
   tasks:
   - build-and-test-and-upload
   - build-and-test-shared-bson
 - name: rhel-70-64-bit
   display_name: "RHEL 7.0 64-bit"
   run_on: rhel70-small
+  expansions:
+    has_packages: true
+    packager_distro: rhel70
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -448,6 +527,10 @@ buildvariants:
 - name: rhel-71-ppc64el
   display_name: "RHEL 7.1 ppc64el"
   run_on: rhel71-power8-test
+  expansions:
+    has_packages: true
+    packager_distro: rhel71
+    packager_arch: ppc64le
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -456,6 +539,10 @@ buildvariants:
 - name: suse12-64
   display_name: "SLES 12 64-bit"
   run_on: suse12-test
+  expansions:
+    has_packages: true
+    packager_distro: suse12
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -466,6 +553,10 @@ buildvariants:
 - name: suse15-64
   display_name: "SLES 15 64-bit"
   run_on: suse15-test
+  expansions:
+    has_packages: true
+    packager_distro: suse15
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -476,6 +567,10 @@ buildvariants:
 - name: suse12-s390x  
   display_name: "SLES 12 s390x"
   run_on: suse12-zseries-test
+  expansions:
+    has_packages: true
+    packager_distro: suse12
+    packager_arch: s390x
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -485,6 +580,10 @@ buildvariants:
 - name: ubuntu1604-arm64
   display_name: "Ubuntu 16.04 arm64"
   run_on: ubuntu1604-arm64-large
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1604
+    packager_arch: arm64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -495,6 +594,10 @@ buildvariants:
 - name: ubuntu1604-s390x
   display_name: "Ubuntu 16.04 s390x"
   run_on: ubuntu1604-zseries-small
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1604
+    packager_arch: s390x
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -504,6 +607,10 @@ buildvariants:
 - name: ubuntu1804-64
   display_name: "Ubuntu 18.04 64-bit"
   run_on: ubuntu1804-test
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1804
+    packager_arch: x86_64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -514,6 +621,10 @@ buildvariants:
 - name: ubuntu1804-arm64
   display_name: "Ubuntu 18.04 arm64"
   run_on: ubuntu1804-arm64-build
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1804
+    packager_arch: arm64
   tasks:
   - clang-tidy
   - build-and-test-and-upload
@@ -524,6 +635,10 @@ buildvariants:
 - name: ubuntu1804-ppc64el
   display_name: "Ubuntu 18.04 ppc64el"
   run_on: ubuntu1804-power8-test
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1804
+    packager_arch: ppc64le
   tasks:
   - build-and-test-and-upload
   - build-and-test-shared-bson
@@ -536,6 +651,10 @@ buildvariants:
 - name: ubuntu1804-s390x
   display_name: "Ubuntu 18.04 s390x"
   run_on: ubuntu1804-zseries-test
+  expansions:
+    has_packages: true
+    packager_distro: ubuntu1804
+    packager_arch: s390x
   tasks:
   - build-and-test-and-upload
   - build-and-test-shared-bson
